### ISSUE TITLE
Alloy: Main Blog page has no Meta Description

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#10]
Stack: Alloy

Request: Add meta description to the main blog page. E. g. a full page view has a meta description taken from the text. The Main Blog page does not have a meta description. If I add one manually, it will be used in all other pages as well.

**Comment by elixirgraphics** [comment]
[As stated on the main page of this repository](https://github.com/elixirgraphics/foundry-feature-requests), this issue tracker for feature requests is for Foundry, Potion and Thunder only, _not Alloy_.
