### ISSUE TITLE
Mega Modal - URL triggering

### ISSUE THREAD

**Issue by jacksona69** [elixirgraphics/foundry-feature-requests#12]
Add the ability to trigger Mega Modal via a URL, so (for example) a Privacy Policy pop-up can be clicked from an initial GDPR/Cookie Notice.

**Comment by elixirgraphics** [comment]
With the way the Modal has to be triggered this is harder than is looks. Would require a couple of `data-` tags on the link. But the Button can be used as a link, it just won't be inline with text. I'll leave this open for now so I know to revisit it though.
