### ISSUE TITLE
Add the option for different text sizes for child stacks at the three responsive breakpoints

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#14]
Stack: Form Pro  

Request: I am using the checkbox child stack to add some legal information before the form can be send.  
<img width="384" alt="image" src="https://user-images.githubusercontent.com/83825712/120698620-926efc00-c4af-11eb-8955-faa002405ffc.png">  

I would like to set a custom font size for this text like the other stacks:  
<img width="287" alt="image" src="https://user-images.githubusercontent.com/83825712/120698758-c5b18b00-c4af-11eb-845a-7834a9a8e19c.png">

**Comment by elixirgraphics** [comment]
✅
