### ISSUE TITLE
Ability to define tag that is wrapped around Accordion title

### ISSUE THREAD

**Issue by annebourdon** [elixirgraphics/foundry-feature-requests#15]
**Stack**: Accordion

**Request**: It would be useful to add the ability to choose the tag that is wrapped around item's accordion-title, like for popover's title (v.2.1.1), instead of a h4.

**Comment by elixirgraphics** [comment]
This would need to be done individually on each of the separate Accordion items. There is not a way to do it with one setting on the parent stack. I don't believe this would be a good implementation of this feature.

**Comment by elixirgraphics** [comment]
✅

Re-thought this. Should be ok even if it is done on an individual basis. Will also allow different header tags within the accordion.
