### ISSUE TITLE
Blog search - nothing returned notice

### ISSUE THREAD

**Issue by Ozian21** [elixirgraphics/foundry-feature-requests#16]
In Alloy when you currently search the blog and no entries are returned it just comes up blank which I think could be confusing for website visitors (it could look like an error).

Please could there be notice that appears when the term returns no posts just saying 'no posts available with that term' or similar so this is clear to the user?

What would be blue sky thinking would be having a notice that says 'no posts available with that term but how about checking out these?' with some blog post summaries appearing underneath the notice. This would keep the visitor on the web page.

**Comment by elixirgraphics** [comment]
This is an Alloy feature request. [As stated on the main page of this repository](https://github.com/elixirgraphics/foundry-feature-requests), this issue tracker is  dedicated to feature requests is for **Foundry**, **Potion** and **Thunder** only, _not_ Alloy.


![CleanShot 2021-06-08 at 10 48 54@2x](https://user-images.githubusercontent.com/2013801/121207327-31e11580-c847-11eb-85cc-191487a0fb03.png)
