### ISSUE TITLE
Alloy: Bypass Alloy Editor Login For Sitelok/Other Solution Users

### ISSUE THREAD

**Issue by TemplateRepo** [elixirgraphics/foundry-feature-requests#18]
Is it possible to include in the Editor stack the ability to bypass the login page, for users who are using an alternative solution?

Or... Add an option that uses Sitelok?

Thanks.

**Comment by elixirgraphics** [comment]
This is an Alloy feature request. [As stated on the main page of this repository](https://github.com/elixirgraphics/foundry-feature-requests), this issue tracker is  dedicated to feature requests is for **Foundry**, **Potion** and **Thunder** only, _not_ Alloy.
