### ISSUE TITLE
Standardised buttons/consistent settings

### ISSUE THREAD

**Issue by jacksona69** [elixirgraphics/foundry-feature-requests#19]
Buttons across any/all Foundry/Thunder/Potion stacks (such as sideslide, form/form pro, modal/mega modal, etc) have standard features of the button stack - eg. icons, shadow, tooltips, etc - for consistent settings and look-and-feel.

Ability to set styling for both normal and hovered button states.

**Comment by elixirgraphics** [comment]
✅
