### ISSUE TITLE
Hero Banner: Property to set the bottom position

### ISSUE THREAD

**Issue by HeikoKanzler** [elixirgraphics/foundry-feature-requests#20]
Can we have a property in the inspector to override the scroll button “bottom” position?

I always struggle with the Hero Banner and the scroll down button. It works perfectly on desktop and (most) Android mobiles, but not on Safari / iOS. The scroll down button is covered by the bottom navigation elements, who are visibile on iOS until first user interaction (window size is reported larger as it actually is… I know)…

As the button has no own class, I can help my self with a bit of custom CSS to query the ID (partially), but this is hacky and interfers with some other stacks, who use a “scroll_button”, too:

![c18c5109272569576f9d4346d3de1e5ce6ff4f8c_2_455x500](https://user-images.githubusercontent.com/5279575/127845099-792a7305-9186-4906-9aba-93d42ad7fe05.jpg)

As the button has no own class, I can help my self with a bit of custom CSS to query the ID (partially), but this is hacky and interfers with some other stacks, who use a “scroll_button”, too:

```css
@media screen and (max-width: 480px) {
	div[id$='scroll_button'] {
		bottom: 150px !important;
	}
}
```

**Comment by elixirgraphics** [comment]
Will appear in Foundry v2.3.7
