### ISSUE TITLE
Nav Bar Pro - Alternate Logo For Sticky Nav

### ISSUE THREAD

**Issue by jonbunkell** [elixirgraphics/foundry-feature-requests#25]
I'd like to be able to set a different logo for sticky nav. 

I was looking to have a nav bar which has a logo with two main colours, but when scrolling the primary logo colour becomes the nav background and the logo changes to just pure white outline.

I've attached a couple of mock ups. 

Thanks

Jon
![image](https://user-images.githubusercontent.com/91335586/134700575-975e2e5a-70fb-48d9-9301-f65ff68a4305.png)

**Comment by elixirgraphics** [comment]
👍
