### ISSUE TITLE
Justified alignement for paragraph stack

### ISSUE THREAD

**Issue by beretrouge** [elixirgraphics/foundry-feature-requests#26]
I request the justified alignement for text using Paragraph Stack.

**Comment by elixirgraphics** [comment]
@beretrouge -- Justified text is not likely to make it as an option. Justified text works well for very few uses in life, but the web is not a good place to use it. Especially now with responsive design. If you'd like some articles on the topic let me know. That said, this is probably not a setting that will be added.
