### ISSUE TITLE
Justified Alignment in Nav Pro and Mega Menu

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#27]
The ability to Horizontally align the navigation items.
Left
Center
Right
Justified
Spaced

The ability to Vertically align navigation items
Top
Bottom
Middle

**Comment by elixirgraphics** [comment]
Not sure I follow. I’ll need greater detail.

**Comment by ajenks1973** [comment]
Sorry,
Left, right, and center are already options. Really just having the justified option would be cool. Example: Justified would evenly space the menu items across the entire container, or page if you weren't using a container, the amount of menu items would determine how much space was between each one. 

Vertically align is for extra thick nav bars giving the option to have the nav items appear at the top, middle, or bottom of the nav bar.

**Comment by elixirgraphics** [comment]
>Vertically align is for extra thick nav bars giving the option to have the nav items appear at the top, middle, or bottom of the nav bar.

This can be done already in a few of the navigation stacks. Navigation Bar Pro uses padding for this:
![CleanShot 2021-10-21 at 08 36 24@2x](https://user-images.githubusercontent.com/2013801/138278498-8a4c4a06-3c6c-47a0-b6d0-b911ce137706.png)

Mega Menu also has a way of doing this, too.

> Left, right, and center are already options. Really just having the justified option would be cool. Example: Justified would evenly space the menu items across the entire container, or page if you weren't using a container, the amount of menu items would determine how much space was between each one.

I've done this in some themes, like Tesla and Tesla Pro for example. Users often complain about this to me for various reasons. The most common being long page names causing problems for their navigation.

Like you I also like this style navigation though. I've built the Icon Bar stack around this idea as well. If you haven't checked it out, give it a look.

I'll keep this in mind for a future stack though.
