### ISSUE TITLE
Shutter - Batch Mode

### ISSUE THREAD

**Issue by atobweb** [elixirgraphics/foundry-feature-requests#28]
Can Shutter be modified to support batch import self hosted videos in perhaps a mp4 / mov format ?

**Comment by elixirgraphics** [comment]
@atobweb -- This Feature Request tracker is for Foundry (including Potion and Thunder Packs). Shutter is a standalone stack and not a part of Foundry, so I am going to close this thread.

Currently I don't have plans to update Shutter to use self-hosted videos. This may change at some point, but it won't be soon as development on some other very large projects is currently taking up development time.
