### ISSUE TITLE
Option to disable Icon on mobile view in Zoom stack

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#3]
**Stack**: Zoom  
  
**Request:** On mobile, the image will not get zoomed, as most of the times, the space is not there and the image is large enough already. But on mobile, the icon is still visible and hides part of the image. As the space on mobile is not large, it tends to hide some important parts of the image.
  
Can you please add an option to hide the icon on mobile?

**Comment by jfuellemann** [comment]
I think this is Thunder, not potion?

**Comment by elixirgraphics** [comment]
Zoom is in Potion Pack.

![CleanShot 2021-05-07 at 11 18 55](https://user-images.githubusercontent.com/2013801/117471608-0ad0b480-af26-11eb-8d5a-a55659cb3b90.png)


I believe you meant Video Zoom. I updated that feature request to reflect that. Thanks.

**Comment by elixirgraphics** [comment]
Done. Included in Potion Pack v2.1.1
