### ISSUE TITLE
Change (replace) icons in Linked List

### ISSUE THREAD

**Issue by wondrousss** [elixirgraphics/foundry-feature-requests#32]
Please! Replace the FontAwesome 4.7 list with the ability to add FontAwesome 5. For example, replace the list with an input field. Sometimes there is a great lack of more icons that are in FA5.

**Comment by elixirgraphics** [comment]
FontAwesome 5 is not currently a part of the Stacks API.

**Comment by elixirgraphics** [comment]
A future version of Foundry will have access to additional icon fonts.

**Comment by wondrousss** [comment]
Thanks for reply!
The future version, what is it, 3.0?

**Comment by elixirgraphics** [comment]
Future version means anything past the current version.
