### ISSUE TITLE
Free elements and Phone number field in the Form Pro stack.

### ISSUE THREAD

**Issue by wondrousss** [elixirgraphics/foundry-feature-requests#34]
1. Please make the all elements in the Form Pro stack not fixed, so that they can be moved or placed in the built-in columns.

2. And if possible, then add a phone number field in different formats. That is, the cursor was placed in the field and the country code specified in the settings and brackets for the first three digits appeared in it (as done on some sites).

**Comment by elixirgraphics** [comment]
✅
