### ISSUE TITLE
Multiple Log In's for Alloy

### ISSUE THREAD

**Issue by JudGreetham** [elixirgraphics/foundry-feature-requests#35]
Loving Alloy however could I ask that different user names and passwords are available to create for multiple contributors to the blog/droplets that are created. Thanks. Justin

**Comment by elixirgraphics** [comment]
Hi @JudGreetham --

This feature request repo is for Foundry only requests, [as noted in the Read Me on the main page of the repo](https://github.com/elixirgraphics/foundry-feature-requests):

> When submitting a feature request please submit them only for Foundry based stacks. That would be any stack in the main Foundry suite, as well as stacks included in the Potion Pack and Thunder Pack addons. _**Please do not submit requests for Alloy, or other stacks and themes here.**_

That said, Alloy v3 does in fact allow two different logins -- a primary and secondary login. Going beyond that would mean overhauling the Editor to work much differently. Right now I'm in the middle of a lot of major updates for Foundry itself, so I won't be able to work on massive updates for Alloy until that is completed.
