### ISSUE TITLE
Let Icon Bar Icons open Pop-ups and Modal Windows

### ISSUE THREAD

**Issue by ChemBob** [elixirgraphics/foundry-feature-requests#36]
HI, I think the title is self-explanatory. I would like to be able to have clicks on an icon in the icon bar open either pop-ups or modals; possibly also other types of links I'm not thinking of at the moment. Having first cup of coffee after waking up late.

Thanks, Bob

**Comment by elixirgraphics** [comment]
If you think of what the “other types” are please update this feature request.

**Comment by elixirgraphics** [comment]
👍
