### ISSUE TITLE
Countdown — Editable in Alloy

### ISSUE THREAD

**Issue by Fitzback666** [elixirgraphics/foundry-feature-requests#37]
Hi Adam!
What I would like see in the next version of « Foundry» is a countdown timer stack editable via Alloy?
A way to let clients edit there countdown themselfe. It is good for site event, landing page, etc.

Thank you!
Fitz

**Comment by elixirgraphics** [comment]
These are Alloy based requests. This Feature Request section is for Foundry based requests only per the Readme on the main page of this repo (https://github.com/elixirgraphics/foundry-feature-requests):

> When submitting a feature request please submit them only for Foundry based stacks. That would be any stack in the main Foundry suite, as well as stacks included in the Potion Pack and Thunder Pack addons. **Please do not submit requests for Alloy, or other stacks and themes here.**
