### ISSUE TITLE
Display content based on date and time editable with «Droplets»

### ISSUE THREAD

**Issue by Fitzback666** [elixirgraphics/foundry-feature-requests#38]
Hi! Would be nice to have a «display content based on date and time stack» with «before» and «after» that client can edit with «Droplet» for the «date & time» and manage text and image with «Embeds». Nice for client with event during the year.

**Comment by elixirgraphics** [comment]
These are Alloy based requests. This Feature Request section is for Foundry based requests only per the Readme on the main page of this repo (https://github.com/elixirgraphics/foundry-feature-requests):

> When submitting a feature request please submit them only for Foundry based stacks. That would be any stack in the main Foundry suite, as well as stacks included in the Potion Pack and Thunder Pack addons. **Please do not submit requests for Alloy, or other stacks and themes here.**
