### ISSUE TITLE
Foundry-Potion Pack FormPro

### ISSUE THREAD

**Issue by digitaljoe-dev** [elixirgraphics/foundry-feature-requests#41]
Two requests:

1. Once a form has been submitted, a custom success message is sent to the person who has submitted the form, or even a standard one will suffice.
2. The IP address of the person filling out the form is (optional?) recorded in order to block the spam farms.

**Comment by elixirgraphics** [comment]
> Once a form has been submitted, a custom success message is sent to the person who has submitted the form, or even a standard one will suffice.

What you're describing sounds like Gated Content. Is that what you're after? Many companies use this as a lead generation sort of method.

> The IP address of the person filling out the form is (optional?) recorded in order to block the spam farms.

Due to GDPR this is probably not something I'd add.

**Comment by elixirgraphics** [comment]
Hey @digitaljoe-dev -- if you could take a second to update this issue with a response to the above that would be helpful in moving forward.

**Comment by digitaljoe-dev** [comment]
> > Once a form has been submitted, a custom success message is sent to the person who has submitted the form, or even a standard one will suffice.
> 
> What you're describing sounds like Gated Content. Is that what you're after? Many companies use this as a lead generation sort of method.
> 
> > The IP address of the person filling out the form is (optional?) recorded in order to block the spam farms.
> 
> Due to GDPR this is probably not something I'd add.

Ok, thanks.

**Comment by elixirgraphics** [comment]
I've worked up a gated content feature for the future. Keep an eye out.

**Comment by digitaljoe-dev** [comment]
> I've worked up a gated content feature for the future. Keep an eye out.

Will do, thanks.
