### ISSUE TITLE
Nav Bar Pro - close menu on mobile when clicked

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#42]
Hi, I am using Nav Bar Pro for some One-Pager sites. The links in the menu are pointing to anchors on the same page. When I use a mobile device, the navigation stays open when a link in the menu is clicked. The customers have to click once again to close the menu. I have received some negative feedback for this extra click. 

Could you please close the menu once a link in the menu is clicked? 

Thank you,
Jan

**Comment by elixirgraphics** [comment]
👍
