### ISSUE TITLE
Dropdown menu support in Navbar Pro

### ISSUE THREAD

**Issue by ColinLondon** [elixirgraphics/foundry-feature-requests#43]
For me, the Navbar Pro stack has better stying than the Navbar or MegaMenu stacks.

But a genuine limitation is the lack of dropdown support from the main link items.

Would be the best menu out there if these were added.

**Comment by elixirgraphics** [comment]
Appreciate that but, Nav Bar Pro was meant to fill an offering that was not already covered by other tools in the lineup when it was released. This isn't a change I'm looking to make to Nav Bar Pro at this time.
