### ISSUE TITLE
Gallery stack: Icon Indicator same as on Zoom stack

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#47]
I would like to see the the same options I have on the Zoom stack Icon Indicator on the Gallery stack: 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/83825712/174490728-2b66cbf6-7791-434d-8081-feec2e8b3c1e.png">

Thank you

**Comment by elixirgraphics** [comment]
Things will be a bit more modular in the future so I think you’ll be happy with the results.
