### ISSUE TITLE
Flat Button 2 - Border Colour on Hover

### ISSUE THREAD

**Issue by jsperron** [elixirgraphics/foundry-feature-requests#48]
Hello. I would like to set a different border colour on hover in order to match the background colour on hover.

That would be nicer not to have a frame on the button on hover. I am trying to create an outline button using Flat Button Stack. Please have a look at the my 2 screenshots.

Thank you !
<img width="248" alt="Capture d’écran, le 2022-07-14 à 15 46 45 (2)" src="https://user-images.githubusercontent.com/85371309/179072386-5696888c-94a5-4496-814c-1f37db1151df.png">
<img width="233" alt="Capture d’écran, le 2022-07-14 à 15 48 32 (2)" src="https://user-images.githubusercontent.com/85371309/179072388-f94e4049-8155-4ceb-b66e-dcf0048dd1a7.png">

**Comment by elixirgraphics** [comment]
Hi @jsperron -- This is a GitHub repo for Foundry feature requests. This is not the appropriate place to request features of non-Foundry tools. Those can be emailed to me, in the future.

That said, I am sorry, but at this time I don't have plans to change how this works in Flat Button.
