### ISSUE TITLE
Icon Bar Features

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#49]
I know it's called the Icon Bar, but It would be great if we had the ability to deselect the icon and put in text instead. Also the abilty to add a content zone. As you can probably guess I'm trying to turn this into a Nav Bar....lol

Thanks for all your hard work

**Comment by elixirgraphics** [comment]
For something like that it might be better to have a more robust, manually curated navigation bar right?

As for the Content Zone -- Not sure what you're looking for there specifically. 

I do not have any Navigation Bar tools that allow for a drop zone in the top tier of the navigation bar itself. The reason being is that with the way a navigation bar is built, it is precarious to just allow any items (read here: code) to be thrown into it willy-nilly. Additionally, most elements will not work layout-wise within a navigation bar, which will lead to user frustration and increased support. So I've weighted the niche need of adding some few possible items into the navigation’s top tier bar against all of the negatives. It’s a bit like the old saying of "give a man enough rope and he will hang himself” — I’m trying to avoid the many pitfalls users would run up against here. 

If I'm mis understanding what you mean by Content Zone for the navigation you're talking about please let me know with some clarifications.

**Comment by ajenks1973** [comment]
I agree, these features would more geared toward a more robust Nav Bar. I understand what your saying about adding a content section/drop zone in the nav. At the end of the day I’m just wanting to build a Nav bar where I can put my logo in the middle and the Nav items evenly spaced on each side.

**Comment by elixirgraphics** [comment]
That layout is a hard one with templated pages. That said, you can create that with the current Navigation Bar Pro tool. Though it will take some finesse getting it right at each breakpoint.

<img width="1116" alt="CleanShot 2022-08-23 at 14 12 24" src="https://user-images.githubusercontent.com/2013801/186233266-85b66e25-05ff-4b44-b9e1-c3c69211c83e.png">

**Comment by ajenks1973** [comment]
This does get me close, if I was able to tell the menu items to take all available space and evenly space themselves apart it would be exactly what I'm looking for.

Thanks
![Screen Shot 2022-08-23 at 5 55 10 PM](https://user-images.githubusercontent.com/89755891/186273714-15d10c5d-a00c-4597-af09-66d59a69b59f.png)

**Comment by ajenks1973** [comment]
I also need one of my menu items to be a dropdown, but I can't do that with Nav Pro.

**Comment by elixirgraphics** [comment]
You’ll want a different navigation tool then. Foundry does not have something to meet your needs.
