### ISSUE TITLE
Backdrop Stack Feature

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#54]
The ability to add patterns or shapes into background in addition to colors and gradients.

**Comment by elixirgraphics** [comment]
Can you expand on this? In what way? What format? Etc??

**Comment by ajenks1973** [comment]
I want to be able to have a background color but as a overlay have the ability to also insert shapes or patterns. Here is a link to a website I created using the Blocs app, at the bottom of the home page right above the footer, you will see a blue section that has faint shapes as a overlay. It gives the section a nice touch over just a plain color. 

www.Cornerstonerockgym.com

**Comment by elixirgraphics** [comment]
It would be less code and fewer graphics to load by just making the tiling graphic as one piece, IMO. That said I'll look into it. But it would require redoing how the overlaid backgrounds work.

**Comment by ajenks1973** [comment]
I had an idea, what if we had the ability to add Custom CSS in the Backdrop stack, I think that would accomplish the samething, Not sure if that's easier or harder to code...lol. But this way someone could use an online CSS generator to create thier own custom background and insert the code into the stack.

**Comment by elixirgraphics** [comment]
Hang in there for major updates to Foundry. 👍

**Comment by ajenks1973** [comment]
Awesome!
