### ISSUE TITLE
Margin / Container Base Stack

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#55]
I think it would be great to have a Margin or Container stack that acts as a utility stack of sorts, where we could create margin or padding presets for the project. This would make it much easier to have consistent padding or margins throughout the project without having to manually setup each margin or container stack in the project. The Source Framework has something like this and I found it very useful while I was test driving it.

**Comment by elixirgraphics** [comment]
Already a part of a future update.
