### ISSUE TITLE
F3 Navigation Menu: Additional breakpoint - Don't.

### ISSUE THREAD

**Issue by TemplateRepo** [elixirgraphics/foundry-feature-requests#57]
Can you add an additional breakpoint to the "mobile below" setting which effectively tells the menu not to break to mobile view?

Use case...

Doing this will introduce the option to add a dropdown with a hamburger icon that is only visible at a predefined screen width, based on the menu item visibility setting. At the same time the desktop menu items can be set to disappear at the same width. Thus the option is there to create an entirely custom desktop/mobile menu. With the mobile menu items in the hamburger dropdown. A la F2 Navbar Pro.

Hope that makes sense!

**Comment by elixirgraphics** [comment]
I don't think I follow completely. What you're describing sounds like what the Mobile Below setting does already on the whole. If you'd like to provide an example to explain what you're after I'll take a look.

**Comment by elixirgraphics** [comment]
Could this just be accomplished with a Drop Down?

**Comment by TemplateRepo** [comment]
I didn't think it was explained too well. I'll do a little demo projects and send it to you.
