### ISSUE TITLE
Breakpoint Font sizing for Buttons

### ISSUE THREAD

**Issue by TemplateRepo** [elixirgraphics/foundry-feature-requests#58]
Can you add breakpoint font sizing options to buttons?

**Comment by elixirgraphics** [comment]
Sorry, that unfortunately isn't how Bootstrap's button styling works. 

You can use Foundry's Visibility to show / hide different buttons at specific breakpoints or Bootstrap's [Display utility classes](https://getbootstrap.com/docs/5.3/utilities/display/) if you'd rather do that route.

**Comment by TemplateRepo** [comment]
Understood.
