### ISSUE TITLE
Typo on Icon Size Labels?

### ISSUE THREAD

**Issue by TemplateRepo** [elixirgraphics/foundry-feature-requests#59]
I think there are some typos on the ixon size settings at the breakpoints. See image.

<img width="325" alt="Screenshot 2023-02-13 at 18 30 59" src="https://user-images.githubusercontent.com/60217150/218544124-ebbccd90-c362-46bb-acc3-56fd55cfc7ea.png">

**Comment by elixirgraphics** [comment]
Thanks. I'll get that fixed.
