### ISSUE TITLE
Ability to use a custom icon for sidebar toggle in Partition Stack

### ISSUE THREAD

**Issue by Jamie249** [elixirgraphics/foundry-feature-requests#6]
Stack: Partitions 

When previewing the sidebar on Mobiles - please can we have a wider selection of Font Awesome icons to choose from

**Comment by elixirgraphics** [comment]
Add more FontAwesome icon options to drop down. Search was requested.

**Comment by elixirgraphics** [comment]
Besides search was there another icon you had in mind?

**Comment by Jamie249** [comment]
Hi Adam, Search icon would be great. For the projet I'm working on the 'File' and 'File-text' icons would be brillant, as I'm going to be putting a selection of forms in the partitons sidebar. 
Thanks Adam

Best wishes

James


James Russell
Yoga Torquay 
www.yogatorquay.co.uk


 

    On Monday, 2 August 2021, 15:54:22 BST, Adam Shiver ***@***.***> wrote:  
 
 


Besides search was there another icon you had in mind?

**Comment by elixirgraphics** [comment]
This should appear in Foundry v2.3.7
