### ISSUE TITLE
F3: Forms does show Subject info even if Subject is set to predefined

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#61]
Found a bug: When Subjet is set to predefined, parts of it still show on the form:
![image](https://user-images.githubusercontent.com/83825712/218850772-50cf45b5-993e-4b3c-b555-826db7a5b9b2.png)

**Comment by elixirgraphics** [comment]
This has been fixed already, correct?

**Comment by jfuellemann** [comment]
Yes :-)--Jan Füllemann Ellmerweg 1331224 PeineTel. 0176 122 43 551Am 19.07.2023 um 16:06 schrieb Adam Shiver ***@***.***>:﻿
This has been fixed already, correct?
