### ISSUE TITLE
SVG Support in ScrollTo Tool

### ISSUE THREAD

**Issue by handshaper** [elixirgraphics/foundry-feature-requests#64]
I would like support for SVG images to be added to the ScrollTo tool, as this is a perfect place to use an SVG.

**Comment by elixirgraphics** [comment]
Please give more details on how what you're thinking here. In what way would SVGs be incorporated into Scroll To?

**Comment by handshaper** [comment]
Currently, the tool allows you to choose between a button or an image. If I choose IMAGE, I can add an SVG as the image, but then I don't have access to the typical settings for the SVG tool; all I get are the ones for an image. I get around this in F3 by using an image and then adding a class to the image to handle hover feedback, but it seems a little clumsier than if I could use an SVG, although I would have to do something similar. With an image I have to be sneaky and apply a background image for the hover effect.
