### ISSUE TITLE
Add  Icons to Foundry 3 Navigation Bar

### ISSUE THREAD

**Issue by regsw** [elixirgraphics/foundry-feature-requests#69]
It would be great to have the ability to add Social tags and other Icons to the navigation bar. My thought is to have the navigation items on one side of the page and the social tags on the navigation bar at the opposite side of the page. Thanks

**Comment by regsw** [comment]
![image](https://github.com/elixirgraphics/foundry-feature-requests/assets/15692711/9ff0278f-3d86-422d-a002-3007e09eef30)

**Comment by elixirgraphics** [comment]
This would likely take reorganizing the way in which the navigation bar works on the whole, so it may not be doable in its current form without breaking users' existing navigation bars already on page. That said I'll take a look for a future update. It could be that it might constitute an additional tool or additional navigation bar for Foundry.

**Comment by elixirgraphics** [comment]
Will be worked into another navigation tool, as adding it in Navigation Bar would cause problems for existing navigations already built.
