### ISSUE TITLE
Problems with Popup

### ISSUE THREAD

**Issue by nicksmith547** [elixirgraphics/foundry-feature-requests#7]
Hi - I have 2 problems with Popover (just purchased Potion so that I could use this, but now I can't).
1. There are no options to style or position the heading or body text that appear in the popup window. The heading is mispositioned with no padding to the edge of the box 
![Popover screen](https://user-images.githubusercontent.com/84126857/118108419-e0747080-b3d7-11eb-9561-9c88b965707a.jpg)
and there no options for font, font size of font weight.
2. The font options provided in the Button stack are not offered in Popover - again pretty essential for me for this to be usable.

**Comment by elixirgraphics** [comment]
If you're having a problem with a stack please post this in the Elixir forum. This repository is _strictly_ for feature requests. I'm going to close this one out, but look forward to your post on the forum.
