### ISSUE TITLE
Divider Tool Enhancment

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#74]
Abilty to set alignment left, right, or center when the width is less than 100%

**Comment by elixirgraphics** [comment]
I'll take a look at this. I don't know that it is possible. Standard `<hr>` tags can be aligned, but the Divider tool is actually a stylized `<div>` in order to add some of the extra features it contains.

**Comment by elixirgraphics** [comment]
Thinking on it a bit I might have a solution for this.

**Comment by elixirgraphics** [comment]
Consider this one done. Will be in the larger update I'm working on now.
