### ISSUE TITLE
Background Tool Enhancement 

### ISSUE THREAD

**Issue by ajenks1973** [elixirgraphics/foundry-feature-requests#76]
Hopefully I'm not driving you crazy with all the feature requests...lol :) 

Having a mode where we could add CSS to the Background tool would be awesome.

**Comment by elixirgraphics** [comment]
Not bothering me at all. I appreciate requests. 

Can you be more specific on this one for me?

**Comment by ajenks1973** [comment]
I'm stealing the idea from the Container Plus stack that Stewart has in Source. It's kind of a niche request but I thought I would throw it out there. Below is a screenshot of the setting in the Container Plus stack.

![CleanShot 2023-12-20 at 22 17 06](https://github.com/elixirgraphics/foundry-feature-requests/assets/89755891/cb09b961-8c20-45b5-85f9-87c86f92268d)

**Comment by elixirgraphics** [comment]
Not sure I'm understanding the use of the Custom CSS field. Foundry has a CSS Classes field at the bottom of each tool which can be used to add your own custom CSS to them:

![CleanShot 2023-12-21 at 08 28 59@2x](https://github.com/elixirgraphics/foundry-feature-requests/assets/2013801/5c606a57-c627-4c5f-9abd-82b97cfe086a)

I think I must be missing something here.

**Comment by ajenks1973** [comment]
Here's an example where I used some custom css to create a background using the Container Plus stack in Source. 

![CleanShot 2023-12-21 at 18 26 21](https://github.com/elixirgraphics/foundry-feature-requests/assets/89755891/7556f63e-8018-4d7e-bd7d-989c8b81f2ba)

**Comment by ajenks1973** [comment]
Here's another example of how I applied custom CSS as the background. There's 3 layers here I was playing with, the CSS background that are the dots, then the blobs site on top of the background, then the Cards site on top. This was done in Foundation. Hopefully this helps. 

![CleanShot 2023-12-21 at 18 35 25](https://github.com/elixirgraphics/foundry-feature-requests/assets/89755891/9b34b641-33e2-4c49-abb2-ab6a454aa9e3)

**Comment by elixirgraphics** [comment]
Yep. Like I said, Foundry can do this already. It just does it more efficiently. You don't have to re-enter all of that CSS in each Container, Background, etc tool that you want to use it with, and heaven forbid you need to make changes in several places... instead you create a class in RW's site-wide CSS field, like so:

![CleanShot 2023-12-21 at 20 09 28@2x](https://github.com/elixirgraphics/foundry-feature-requests/assets/2013801/32f2f57b-32b1-48cf-98f7-8c1159c59d98)

Then add that class name in the Classes field(s) in Foundry's tools, and viola, you've just styled your elements with your custom CSS. And if you change that code in the site-wide CSS field, it gets applied everywhere you're applying that class name.

Hopefully that makes sense. If not, shoot me a copy of a test project file and include your custom css for me and I'll show you what I mean.

**Comment by ajenks1973** [comment]
I've alway's wondered how the CSS section worked, with my very limited coding knowledge it seemed intimidating so I didn't mess with it. But how you explained it is great, the concept is very simple, I'm creating my own classes and then I'm able to reference those classes throughout the site. I should be able to use this same concept if I wanted a certain shadow on an element correct? 

I understand the concept but I must be doing something wrong because I can't seem to make it work, so I'm going to take you up on your offer and send you the project file for you to take a look at.

**Comment by elixirgraphics** [comment]
Remove the `/*` and the `*/` from your code. Those are comment markers. I used them to show that you place your code between the two curly brackets. So when you insert your code replace the entire `/* Your CSS goes here. */` with your code. essentially you just turned your code into a comment. 👍

**Comment by ajenks1973** [comment]
Got it, thank you. I'm already playing around with different shadows on elements. This is so cool!!!

**Comment by elixirgraphics** [comment]
Awesome! CSS is my favorite thing about web design. ❤️
