### ISSUE TITLE
Alloy: Custom meta descriptions

### ISSUE THREAD

**Issue by jfuellemann** [elixirgraphics/foundry-feature-requests#9]
Stack: Alloy  
  
Request:  Allow custom meta descriptions. Currently, the meta descriptions are created automatically. They are too long in most cases for CTR reasons. They should be around 1000px. Using custom descriptions, I can control the content.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/83825712/119882727-03059e00-bf2f-11eb-9904-263184a47fd1.png">

**Comment by elixirgraphics** [comment]
[As stated on the main page of this repository](https://github.com/elixirgraphics/foundry-feature-requests), this issue tracker for feature requests is for Foundry, Potion and Thunder only, _not Alloy_.
